### ISSUE TITLE
Add Password for Encrypted Budgets

### ISSUE THREAD

**Issue by ThePatrickHoover** [duplaja/actual-simplefin-sync#5]
![image](https://github.com/duplaja/actual-simplefin-sync/assets/43894671/03584b0e-af19-4b22-86e4-13265d67cadb)

**Comment by duplaja** [comment]
Thank you!

Notes, to jog my memory later: password is passed as an extra parameter in downloadBudget, from the Actual Budget API. Will need to add a setting, and handle conditionally vs non-encrypted

**Comment by duplaja** [comment]
@ThePatrickHoover This should be good now! If you have the time and want to pull and give it a try, let me know how it goes!

**Comment by tjfinlinson** [comment]
Just gave this a try and I received this error.

```
Initializing Actual Budget...
C:\Github\actual-simplefin-sync\node_modules@actual-app\api\dist\app\bundle.api.js:32087
                        throw new Error(File ${file.name} is encrypted. Please provide a password.);

Error: File My Budget is encrypted. Please provide a password.
    at handlers.api/download-budget (C:\Github\actual-simplefin-sync\node_modules@actual-app\api\dist\app\bundle.api.js:32087:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by duplaja** [comment]
@tjfinlinson Should be good now, just pushed a fix. There was an issue with initial validation that would cause the encryption key to save as an empty string.

**Comment by tjfinlinson** [comment]
I can verify that the change got it validating and took me all the way through to mapping the accounts I have set up in SimpleFin. Thanks!
