### ISSUE TITLE
Helpful Output if trying to re-use Setup Token

### ISSUE THREAD

**Issue by tjfinlinson** [duplaja/actual-simplefin-sync#7]
As soon as you enter the Setup Token from your SimpleFin App, it is immediately posts back to SimpleFin and gets the access token for read only access to your bank data. If you attempt to use that Setup Token again, the process will fail. 

Having the process report what happened and give you a tip on what to do would be a nice addition.

**Comment by duplaja** [comment]
Ok, this should be a bit better now. 

As long as the initial setup token validates, it should save and store the returned access key, so repeating with the same setup won't cause any issues. (will just use the pre-stored access key)

I removed the piece that caused it to not save any inputs until all tests had passed, and then just added additional checks before it moves on from settings.
