### ISSUE TITLE
E2EE budgets hosted on fly.io cannot sync

### ISSUE THREAD

**Issue by micmintran** [duplaja/actual-simplefin-sync#9]
Full error for reference if needed (after running app.js a second time with 'last synced' deleted from config.json):
https://gist.github.com/micmintran/82e3f961fc8bc9786ac9414ea6f43cd3

Message received on fly.io machine monitoring:
`dfw [warn] Instance xxxxx reached hard limit of 25 concurrent connections. This usually indicates your app is not closing connections properly or is not closing them fast enough for the traffic levels it is handling. Scaling resources, number of instances or increasing your hard limit might help.`

Actual also does not update its transactions.

Deleting budget folder allows app.js to run smoothly — budget folder is recreated, Actual still not updated

Editing 'last synced' to Nov. 6 also allows app.js to run smoothly, Actual still not updated.

**Comment by duplaja** [comment]
I have worked out auto-deleting after first run, so the budget folder issue should be better. I've also made some changes to how the connections spawn, so you shouldn't run into the concurrent connections issue anymore, hopefully.

I don't have a fly.io setup at the moment to test, so if you are willing to, it would be helpful! I've merged in those changes.

**Comment by duplaja** [comment]
Closing this one out. Fixed by reworking the connection order to reduce new connections, and some extra handling of encrypted budgets.
